import { useEffect } from 'react'
import { VoiceOrb } from './components/VoiceOrb'
import { LiveWaveform } from './components/LiveWaveform'
import { MessageFeed } from './components/MessageFeed'
import { StatusIndicator } from './components/StatusIndicator'
import { useLiveKitAgent } from './hooks/useLiveKitAgent'
import { useStore } from './lib/store'

function App() {
  // Get URL parameters for LiveKit connection
  //   - livekit_url: LiveKit server URL (wss://...)
  //   - token: LiveKit room token (JWT)
  const params = new URLSearchParams(window.location.search)
  const livekitUrl = params.get('livekit_url') || params.get('livekit')
  const livekitToken = params.get('token') || params.get('livekit_token')
  const hasConnectionParams = !!(livekitUrl && livekitToken)

  // Initialize LiveKit agent hook
  const agent = useLiveKitAgent()

  const {
    agentState,
    agentConnected,
    inputVolume,
    outputVolume,
    messages,
    toolCalls
  } = useStore()

  // Connect to LiveKit when parameters are available
  useEffect(() => {
    if (livekitUrl && livekitToken) {
      agent.connect(livekitUrl, livekitToken)
    }

    return () => {
      agent.disconnect()
    }
  }, [livekitUrl, livekitToken])

  // Get connection status
  const { isConnected, isConnecting, isReconnecting, error } = agent

  return (
    <div className="min-h-screen bg-gradient-to-b from-white via-gray-50 to-gray-100 flex flex-col items-center justify-center overflow-hidden">
      {/* Subtle background gradient overlay */}
      <div className="absolute inset-0 bg-gradient-radial from-transparent via-transparent to-gray-100/50 pointer-events-none" />

      {/* Main content container */}
      <div className="relative z-10 w-full max-w-2xl px-6 py-8 flex flex-col items-center">

        {/* Status indicator - top right */}
        <div className="absolute top-4 right-4">
          <StatusIndicator
            isConnected={isConnected}
            isConnecting={isConnecting || isReconnecting}
            agentConnected={agentConnected}
            error={error}
          />
        </div>

        {/* Connection badge */}
        {hasConnectionParams && (
          <div className="absolute top-4 left-4">
            <span className="px-2 py-1 text-xs font-medium rounded-full bg-purple-100 text-purple-700">
              LiveKit
            </span>
          </div>
        )}

        {/* Hero: Voice Orb */}
        <div className="flex-1 flex items-center justify-center py-12">
          <VoiceOrb
            agentState={agentState}
            inputVolume={inputVolume}
            outputVolume={outputVolume}
          />
        </div>

        {/* Input waveform - shows when listening */}
        {agentState === 'listening' && (
          <div className="w-full max-w-md mb-8 animate-fade-in">
            <LiveWaveform
              active={true}
              barColor="rgba(139, 92, 246, 0.6)"
              height={48}
            />
          </div>
        )}

        {/* Agent state label */}
        <div className="mb-8 text-center">
          <p className="text-sm font-medium text-gray-400 uppercase tracking-wider">
            {agentState === 'listening' && 'Listening...'}
            {agentState === 'thinking' && 'Processing...'}
            {agentState === 'speaking' && 'Speaking...'}
            {!agentState && (
              isConnected
                ? (agentConnected ? 'Ready' : 'Waiting for agent...')
                : isReconnecting
                  ? 'Reconnecting...'
                  : 'Disconnected'
            )}
          </p>
        </div>

        {/* Message feed with blur cycling */}
        <div className="w-full">
          <MessageFeed
            messages={messages}
            toolCalls={toolCalls}
          />
        </div>

        {/* Connection prompt when no parameters */}
        {!hasConnectionParams && (
          <div className="mt-8 p-6 bg-white/60 backdrop-blur-sm rounded-2xl border border-gray-200/50 max-w-md">
            <h3 className="text-lg font-semibold text-gray-800 mb-2">
              Connect to Voice Agent
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              Add URL parameters to connect via LiveKit:
            </p>
            <code className="block p-3 bg-gray-100 rounded-lg text-xs font-mono text-gray-700 break-all">
              ?livekit_url=wss://your-project.livekit.cloud&token=JWT_TOKEN
            </code>
            <p className="text-xs text-gray-500 mt-3">
              The token is generated by your backend when joining a LiveKit room.
            </p>
          </div>
        )}

        {/* Error display */}
        {error && (
          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl">
            <p className="text-sm text-red-600">{error}</p>
          </div>
        )}
      </div>

      {/* SYNRG branding - bottom */}
      <div className="absolute bottom-6 text-center">
        <span className="text-2xl font-bold tracking-[0.3em] bg-gradient-to-r from-violet-500 to-cyan-500 bg-clip-text text-transparent">
          SYNRG
        </span>
        <p className="text-xs text-gray-400 mt-1 tracking-wider">
          VOICE ASSISTANT
        </p>
      </div>
    </div>
  )
}

export default App
